# Generated by Django 5.0.6 on 2024-06-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentdata',
            name='date',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='sunrise',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='sunset',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='futureday',
            name='date',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='futurehour',
            name='date',
            field=models.BigIntegerField(),
        ),
    ]
